### ISSUE TITLE
create tutorial video

### ISSUE THREAD

**Issue by Stephanieani** [zuri-training/Team-69-Product-design#17]

**Comment by Ariwaking** [comment]
hey @Stephanieani , here's the link to the tutorial video I created using canva


https://www.canva.com/design/DAFIIKDxMiA/Q-J6SfE1EhdPj1z0i-Y_6w/watch?utm_content=DAFIIKDxMiA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
